class Field:
    def zero(self): ...
    def one(self): ...
    def add(self, a, b): ...
    def sub(self, a, b): ...
    def mul(self, a, b): ...
    def inv(self, a): ...
    def pow(self, a, n): ...
